version: '3'

services:
  backend:
    image: link-extractor-api:1.0
    ports:
      - "5000:5000"
  web:
    image: php:7-apache
    ports:
      - "80:80"
    environment:
      - API_ENDPOINT=http://backend:5000/api/
    volumes:
      - ./www:/var/www/html
