apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: ine
spec:
  limits:
  - default:
      cpu: 100m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    max:
      cpu: 1000m
      memory: 5Gi
    min:
      cpu: 5m
      memory: 5Mi
    type: Container

---

apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: management
spec:
  limits:
  - default:
      cpu: 100m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    max:
      cpu: 1000m
      memory: 5Gi
    min:
      cpu: 5m
      memory: 5Mi
    type: Container
