apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: wdatp-infra-system
spec:
  limits:
  - default:
      cpu: 100m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    max:
      cpu: 3000m
      memory: 8Gi
    min:
      cpu: 5m
      memory: 5Mi
    type: Container
