from http.server import BaseHTTPRequestHandler,HTTPServer
import socketserver


class MyHTTPRequestHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        # Sending an '200 OK' response
        self.send_response(200)
        # Setting the header
        self.send_header("Content-type", "text/html")
        # Whenever using 'send_header', you also have to call 'end_headers'
        self.end_headers()
        # Some custom HTML code, possibly generated by another function
        html = f"<html><head></head><body><h1>Hello World!</h1></body></html>"
        # Writing the HTML contents with UTF-8
        self.wfile.write(bytes(html, "utf8"))
        return

def run(server_class=HTTPServer, handler_class=MyHTTPRequestHandler,port=8080):
    server_address = ('', port)
    httpd = server_class(server_address, handler_class)
    httpd.serve_forever()

if __name__ == "__main__":
    from sys import argv
    if len(argv) == 2:
        run(port=int(argv[1]))
    else:
        run()

